[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Ian Calvert", email = "ian.calvert@cardstack.com"},
]
dependencies = [
    "boto3",
    "cloudpathlib[s3]>=0.7.1",
    "pyyaml>=6.0",
    "cachetools>=5.0.0",
    "pyarrow>=8.0.0",
]
requires-python = ">=3.9"
license = {text = "MIT"}
[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
