name: Manual Deploy [cardie]

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git branch/tag
        required: true
      environment:
        description: Deployment environment
        required: false
        default: staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up env
        env:
          INPUT_ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          if [ "$INPUT_ENVIRONMENT" != "staging" ]; then
            echo "unrecognized environment"
            exit 1;
          fi

      - name: Set up yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Deploy cardie
        uses: ./.github/actions/deploy-cardie
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_WAYPOINT_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_WAYPOINT_AWS_SECRET }}
          WAYPOINT_SERVER_TOKEN: ${{ secrets.STAGING_WAYPOINT_SERVER_TOKEN }}
          WAYPOINT_SERVER_ADDR: ${{ secrets.STAGING_WAYPOINT_SERVER_ADDR }}
        with:
          ref: ${{ github.event.inputs.ref }}
