name: CI [cardpay-subgraph]
on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/cardpay-sdk/**'
      - 'packages/cardpay-subgraph/**'
      - 'packages/eslint-config/**'

jobs:
  test:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: volta-cli/action@v1
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn global add lerna
    - run: yarn --prefer-offline
    - run: yarn codegen
    - run: yarn lint:deps
    - run: yarn lint:js:pkg cardpay-subgraph
    - run: yarn build
