name: CI [ember-shared]

on:
  pull_request:
    paths:
      - "packages/ember-shared/**"
      - 'packages/eslint-config/**'
      - ".github/workflows/pr-ember-shared.yml"
      - "package.json"
      - "yarn.lock"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  id-token: write

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Set up node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/ember-shared/*/node_modules
            packages/firebase-functions/*/functions/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - name: Run tests
        run: yarn test:ember-shared
