name: CI [web-client]

on:
  push:
    branches: [main]

jobs:
  test:
    name: Build & Lint & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: volta-cli/action@v1
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn global add lerna
    - run: yarn --prefer-offline
    - run: yarn lint
    - run: yarn test

  change_check:
    name: Check which packages changed
    needs: test
    runs-on: ubuntu-latest
    outputs:
      hub: ${{ steps.filter.outputs.hub }}
      web_client: ${{ steps.filter.outputs.web_client }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          hub:
            - 'packages/hub/**'
            - 'packages/did-resolver/**'
          web_client:
            - 'packages/web-client/**'
            - 'packages/cardpay-sdk/**'
            - 'packages/did-resolver/**'

  deploy-hub-staging:
    name: Deploy hub to staging cluster via waypoint
    needs: change_check
    if: ${{ needs.change_check.outputs.hub == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
    - name: Install apt packages including waypoint
      run: |
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install awscli waypoint docker-ce
    - name: Configure waypoint client
      run: waypoint context create -server-addr=${{ secrets.WAYPOINT_SERVER_ADDR }} -server-auth-token=${{ secrets.WAYPOINT_AUTH_TOKEN }} -server-tls=true -server-tls-skip-verify=false -set-default
    - uses: volta-cli/action@v1
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn global add lerna
    - run: yarn --prefer-offline
    - name: Deploy hub
      run: waypoint up --app=hub -plain
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.WAYPOINT_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.WAYPOINT_AWS_SECRET }}
        AWS_DEFAULT_REGION: us-east-1

  deploy-web-client-staging:
    name: Deploy web-client to S3 staging bucket
    needs: change_check
    if: ${{ needs.change_check.outputs.web_client == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn global add lerna
    - run: yarn --prefer-offline
    - name: Run ember-cli-deploy
      run: yarn deploy:web-client:staging
      env:
        EMBER_DEPLOY_AWS_ACCESS_KEY: ${{ secrets.STAGING_EMBER_DEPLOY_AWS_ACCESS_KEY }}
        EMBER_DEPLOY_AWS_ACCESS_SECRET: ${{ secrets.STAGING_EMBER_DEPLOY_AWS_ACCESS_SECRET }}
